"""The retention policy executed, not described.

    python run_retention.py

`src/retention.py` had the three tiers, the dispute-age validation and an
`ArchiveStore` that could hold and retrieve. Nothing called any of it. A
retention policy nothing executes is a document, and the failure is quiet:
everything stays hot, storage grows, and the first anyone notices is a cost
review -- or the policy gets run by hand once, unevenly, and nobody can say
which dates were archived and which were dropped.

This runs `src/archival_job.py` across a book that spans eight years, so every
tier boundary is crossed by real data rather than asserted:

  * days inside the hot window stay queryable
  * days past it are archived, verified and removed from hot storage
  * a chargeback arrives for a transaction deep in the archive and is EVIDENCED
  * days past the legal floor become purge-eligible and are purged only on an
    explicit flag, with the deletion recorded
  * every date the system has ever seen is accounted for in one of the tiers

Writes docs/RETENTION.md.
"""
from __future__ import annotations

import shutil
import sqlite3
import sys
from datetime import date, timedelta
from pathlib import Path

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT))

from src.archival_job import coverage_report, evidence_for, run_archival
from src.retention import ArchiveStore, RetentionPolicy
from src.service import SCHEMA

ARCHIVE_DIR = ROOT / "data" / "archive"
AS_OF = "2026-08-24"
PER_DAY = 300


def _book() -> tuple:
    """A settled book spanning eight years, one date per tier boundary plus
    enough volume for the compression figure to mean something."""
    con = sqlite3.connect(":memory:")
    con.row_factory = sqlite3.Row
    con.executescript(SCHEMA)

    as_of = date.fromisoformat(AS_OF)
    dates = []
    for age in (1, 10, 40,           # hot   (<= 45 days)
                90, 300, 540,        # archive (<= 545)
                800, 1500, 2400,     # cold  (<= 2555, past disputes)
                2600, 3000):         # purgeable (past the 7-year floor)
        dates.append((as_of - timedelta(days=age)).isoformat())

    for d in dates:
        for i in range(PER_DAY):
            ref = "{}-{:04d}".format(d.replace("-", ""), i)
            amount = 1_000 + (i * 137) % 90_000
            con.execute(
                "INSERT INTO txn (ref, auth_date, amount_minor, currency,"
                " settled_minor, fee_minor, state) VALUES (?,?,?,?,?,?,?)",
                (ref, d, amount, "USD", amount, 30 + amount * 29 // 10_000,
                 "settled"))
            con.execute(
                "INSERT INTO match_event (ref, file_id, line_no, rule,"
                " from_state, to_state, amount_minor) VALUES (?,?,?,?,?,?,?)",
                (ref, "STL{}".format(d.replace("-", "")), i, "exact_ref",
                 "pending", "settled", amount))
    con.commit()
    return con, dates


def main() -> int:
    if ARCHIVE_DIR.exists():
        shutil.rmtree(ARCHIVE_DIR)
    con, dates = _book()
    store = ArchiveStore(ARCHIVE_DIR)
    policy = RetentionPolicy()

    total_rows = len(dates) * PER_DAY

    L = []
    add = L.append
    add("# SE-2 — the retention policy, executed")
    add("")
    add("Generated by `run_retention.py` over a book of {:,} settled".format(total_rows))
    add("transactions across {} business dates spanning eight years, so every".format(
        len(dates)))
    add("tier boundary is crossed by real data rather than asserted.")
    add("")
    add("| policy | days |")
    add("|---|---|")
    add("| hot (indexed, queried daily) | {} |".format(policy.hot_days))
    add("| archive (compressed, retrievable) | {} |".format(policy.archive_days))
    add("| legal floor (minimum time to KEEP) | {:,} |".format(policy.legal_floor_days))
    add("")

    # ------------------------------------------------------- dry run first
    plan = run_archival(con, store, AS_OF, policy, dry_run=True)
    add("## 1. Dry run — what it would do, before it does it")
    add("")
    add("| | |")
    add("|---|---|")
    add("| dates it would archive | {} |".format(len(plan.archived_dates)))
    add("| rows it would move | {:,} |".format(plan.archived_rows))
    add("| dates eligible to purge | {} |".format(len(plan.purge_eligible)))
    add("| rows still hot afterwards | {:,} |".format(
        con.execute("SELECT COUNT(*) c FROM txn").fetchone()["c"]))
    add("")
    add("A job that deletes should be able to say what it would do first. The")
    add("hot count above is unchanged, which is the point of printing it.")
    add("")

    # ------------------------------------------------------------ real run
    res = run_archival(con, store, AS_OF, policy)
    hot_after = con.execute("SELECT COUNT(*) c FROM txn").fetchone()["c"]

    add("## 2. The archival pass")
    add("")
    add("| | |")
    add("|---|---|")
    add("| dates archived | {} |".format(len(res.archived_dates)))
    add("| rows moved | {:,} |".format(res.archived_rows))
    add("| rows remaining hot | {:,} |".format(hot_after))
    add("| uncompressed | {:,} bytes |".format(res.hot_bytes))
    add("| gzipped archive | {:,} bytes |".format(res.archive_bytes))
    add("| compression | **{:.1f}x** |".format(res.compression_ratio))
    add("| wall clock | {:.2f}s |".format(res.seconds))
    add("")
    add("The hot store went from {:,} rows to {:,} — a {:.0%} reduction — and".format(
        total_rows, hot_after, 1 - hot_after / total_rows))
    add("nothing was lost, because every archive file was read back and its row")
    add("count checked **before** the hot copy was deleted. Any other order has")
    add("a window where a crash loses the data, and \"we archived it\" with")
    add("nothing at the other end is worse than not archiving.")
    add("")

    # ------------------------------------------------------- idempotency
    again = run_archival(con, store, AS_OF, policy)
    add("## 3. Running it again")
    add("")
    add("| | first run | second run |")
    add("|---|---|---|")
    add("| dates archived | {} | {} |".format(
        len(res.archived_dates), len(again.archived_dates)))
    add("| rows moved | {:,} | {:,} |".format(
        res.archived_rows, again.archived_rows))
    add("| skipped, already archived | {} | {} |".format(
        len(res.skipped_already_archived), len(again.skipped_already_archived)))
    add("")
    add("It runs daily and will be re-run after failures. The dangerous version")
    add("of non-idempotency here is not a duplicate file — it is that the hot")
    add("rows are already gone, so a second unguarded pass would write an")
    add("**empty archive over a good one**.")
    add("")
    add("Getting this right required a fix that is worth stating plainly: the")
    add("job's date list originally came from hot storage alone, so it forgot a")
    add("date the moment it archived it. Nothing already archived could be")
    add("reported as already archived, and — far worse — nothing already")
    add("archived could ever be **purged**, because the purge branch only ever")
    add("saw dates still sitting hot. The list is now the union of both tiers.")
    add("")

    # --------------------------------------------------------- retrieval
    archived_date = res.archived_dates[len(res.archived_dates) // 2]
    ref = "{}-0100".format(archived_date.replace("-", ""))
    hot_date = max(d for d in dates if d not in res.archived_dates
                   and d not in res.purge_eligible)
    hot_ref = "{}-0100".format(hot_date.replace("-", ""))

    found_hot = evidence_for(con, store, hot_ref, search_dates=dates)
    found_cold = evidence_for(con, store, ref, search_dates=dates)

    add("## 4. A dispute arrives for archived data")
    add("")
    add("The reason the archive exists. A chargeback carries a reference and no")
    add("idea which tier the data is in, so the lookup covers both and says")
    add("which one answered.")
    add("")
    add("| reference | tier | business date | amount | provenance | lookup |")
    add("|---|---|---|---|---|---|")
    for f in (found_hot, found_cold):
        ev = f["events"][0]
        add("| `{}` | **{}** | {} | {:,} | {} line {} rule `{}` | {:.3f}s |".format(
            f["ref"], f["tier"], f.get("auth_date", f.get("found_in")),
            f["amount_minor"], ev["file_id"], ev["line_no"], ev["rule"],
            f["lookup_seconds"]))
    add("")
    add("Both answers are evidence. The archived one took {:.0f}x longer to".format(
        found_cold["lookup_seconds"] / max(found_hot["lookup_seconds"], 1e-9)))
    add("find, which is the trade the tier exists to make — the archive is")
    add("deliberately unindexed, because indexing it would cost most of what")
    add("archiving saved. An hour to answer a dispute is acceptable; losing the")
    add("dispute is not.")
    add("")
    add("Note what travels with the row. Archiving the amount alone would keep")
    add("the half a representment does not need and lose the half it does:")
    add("**which file said so, on which line, under which rule.**")
    add("")

    # ------------------------------------------------------------- purge
    add("## 5. Purge — a different verb, and a separate flag")
    add("")
    add("| | |")
    add("|---|---|")
    add("| dates past the legal floor | {} |".format(len(res.purge_eligible)))
    add("| purged by the runs above | {} |".format(len(res.purged_dates)))
    add("")
    add("Zero, because `purge` defaults to off. Archiving is reversible and")
    add("purging is not, so they are two verbs taking two flags. A single")
    add("`run_retention()` that quietly deletes past the floor is how a routine")
    add("job becomes an incident.")
    add("")
    add("A second thing this run made explicit, and it cost two failing tests to")
    add("find: **a purgeable date is never archived on the way past the floor.**")
    add("Archiving data you are already permitted to delete buys nothing, so it")
    add("is left where it is and marked eligible — which means purge has to")
    add("reach into *hot* storage, not only into the archive. A purge that")
    add("deletes only archive files would leave those rows in place while")
    add("logging a deletion that did not fully happen.")
    add("")

    purged = run_archival(con, store, AS_OF, policy, purge=True)
    add("Run with the flag:")
    add("")
    add("| business date | rows | bytes | reason |")
    add("|---|---|---|---|")
    for e in store.purge_history():
        add("| {} | {:,} | {:,} | {} |".format(
            e["business_date"], e["rows"], e["bytes"], e["reason"]))
    add("")
    add("The purge log is the part people skip. Deleting data without recording")
    add("that you deleted it turns a defensible policy into an unexplainable")
    add("hole — an auditor asking what happened to a record needs a better")
    add("answer than \"we have no idea\".")
    add("")

    # ---------------------------------------------------------- coverage
    cov = coverage_report(con, store, AS_OF, policy)
    add("## 6. Is every date accounted for?")
    add("")
    add("The question an auditor asks is not *what is your policy* but *where is")
    add("the data for 14 March*.")
    add("")
    add("| tier | dates |")
    add("|---|---|")
    add("| hot | {} |".format(cov["hot_dates"]))
    add("| archived | {} |".format(cov["archived_dates"]))
    add("| purged, on record | {} |".format(cov["purged_dates"]))
    add("| **total accounted** | **{}** of {} |".format(
        cov["total_accounted"], len(dates)))
    add("")
    if cov["duplicated"]:
        add("**{} date(s) appear in two tiers at once**: {}. That is not a hole".format(
            len(cov["in_both_tiers"]), ", ".join(cov["in_both_tiers"])))
        add("but the opposite failure — a delete that did not happen — and it")
        add("means the data could be found twice and disagree with itself.")
    else:
        add("No date appears in two tiers, and none is missing from all three. A")
        add("date that is neither hot nor archived nor in the purge log is an")
        add("unexplained hole, and this is the check that finds one.")
    add("")

    # -------------------------------------------------- policy validation
    add("## 7. Is the policy long enough?")
    add("")
    add("Retention derived from a storage budget is a decision to lose winnable")
    add("disputes. Derived from the observed dispute-age distribution, it is a")
    add("control. `RetentionPolicy.validate_against` checks one against the")
    add("other:")
    add("")
    add("| observed max dispute age | verdict |")
    add("|---|---|")
    for age in (120, 540, 700):
        v = policy.validate_against(age)
        add("| {} days | {} (margin {:+,} days) |".format(
            age, v["verdict"], v["margin_days"]))
    add("")
    add("The third row is the one to look at. An archive window shorter than the")
    add("observed dispute tail means evidence will be missing exactly when it is")
    add("needed, and the policy will look fine on every metric until the first")
    add("dispute that reaches past it.")

    doc = "\n".join(L)
    (ROOT / "docs").mkdir(exist_ok=True)
    (ROOT / "docs" / "RETENTION.md").write_text(doc, encoding="utf-8")
    print(doc)
    print()
    print("wrote docs/RETENTION.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
