"""Render the operator view from a real settled book.

    python run_dashboard.py

`README.md` listed this as open: "The API returns the numbers; nothing renders
them, and there is no alert rule on aged breaks or fee variance."

This builds a real book, runs the real reconciliation, receives real
chargebacks, and renders the page from what comes out. Writes
`docs/dashboard.html` — openable in a browser — and `docs/DASHBOARD.md`.

The design constraint is in `src/dashboard.py` and worth repeating: every
threshold on the page is imported from the module that owns it. A dashboard
with its own copy of the rules is a second implementation of them, and the two
drift until the screen and the system disagree about what is wrong. The screen
wins, because the screen is what people look at.
"""
from __future__ import annotations

import shutil
import sqlite3
import sys
from datetime import date, timedelta
from pathlib import Path

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT))

from src.break_queue import TIERS
from src.chargebacks import ChargebackBook, EVIDENCE_WINDOW_DAYS
from src.dashboard import build, render_html
from src.dispute_pack import DEFAULT_MATERIALITY_MINOR
from src.files import DATA, generate, parse
from src.service import Service

AS_OF = "2026-05-05"
WORK = ROOT / "data" / "dashboard"


def main() -> int:
    if WORK.exists():
        shutil.rmtree(WORK)
    WORK.mkdir(parents=True, exist_ok=True)

    internal, files, _dup = generate(n_days=6, per_day=250, seed=17)
    svc = Service()
    svc.load_internal(internal)
    for f in sorted(files):
        if f.stem.startswith("STL"):
            try:
                svc.ingest(f)
            except Exception:                                # noqa: BLE001
                pass

    con = sqlite3.connect(":memory:")
    con.row_factory = sqlite3.Row
    book = ChargebackBook(con)

    # Real chargebacks against real refs, spread across the deadline range so
    # every urgency band is exercised by the policy rather than by a flag.
    refs = [r["ref"] for r in svc.con.execute(
        "SELECT ref FROM txn ORDER BY ref LIMIT 40").fetchall()]
    reasons = list(EVIDENCE_WINDOW_DAYS)
    as_of = date.fromisoformat(AS_OF)
    for i, ref in enumerate(refs):
        reason = reasons[i % len(reasons)]
        received = (as_of - timedelta(days=(i % 14))).isoformat()
        book.receive(ref, "CBFILE", i, reason, 2_000 + (i * 7919) % 400_000,
                     "USD", received, None)

    rows = [dict(r) for r in con.execute(
        "SELECT ref, reason_code, amount_minor, evidence_due_on, state"
        " FROM chargeback").fetchall()]

    view = build(aged_breaks=svc.aged_breaks(AS_OF),
                 fee_summary=svc.fee_variance_summary(),
                 chargebacks=rows, as_of=AS_OF,
                 state_counts=svc.state_counts())
    page = render_html(view)

    (ROOT / "docs").mkdir(exist_ok=True)
    (ROOT / "docs" / "dashboard.html").write_text(page, encoding="utf-8")

    L = []
    add = L.append
    add("# SE-2 — the operator dashboard")
    add("")
    add("Generated by `run_dashboard.py` from a real settled book: {:,} internal".format(
        len(internal)))
    add("transactions, real reconciliation, {} real chargebacks. The rendered".format(
        len(rows)))
    add("page is `docs/dashboard.html` and is served live at `/dashboard`.")
    add("")
    add("`README.md` listed this as open: *the API returns the numbers; nothing")
    add("renders them, and there is no alert rule on aged breaks or fee")
    add("variance*.")
    add("")

    add("## The design constraint: thresholds are imported, never re-typed")
    add("")
    add("| what the page colours red | where the number comes from |")
    add("|---|---|")
    add("| break tiers | `break_queue.TIERS` via `tier_for()` |")
    add("| fee materiality | `dispute_pack.DEFAULT_MATERIALITY_MINOR` |")
    add("| evidence windows | `chargebacks.EVIDENCE_WINDOW_DAYS` |")
    add("| worth defending | `chargebacks.WINNABLE` |")
    add("")
    add("This is the one a dashboard usually gets wrong. Someone tunes a")
    add("threshold in the code, the dashboard keeps the old one, and for months")
    add("the screen and the system disagree about what is wrong — **and the")
    add("screen wins, because the screen is what people look at.** A dashboard")
    add("with its own copy of the rules is a second implementation of them.")
    add("")
    add("A test asserts the imports are present AND that no tier boundary")
    add("appears as a literal anywhere in the module; another moves a boundary")
    add("at runtime and checks the alert moves with it.")
    add("")

    add("## What it shows, and what it deliberately does not")
    add("")
    add("| | |")
    add("|---|---|")
    add("| **pages** | **{}** |".format(view["pages"]))
    add("| alerts total | {} |".format(len(view["alerts"])))
    add("| open breaks | {:,} |".format(view["break_count"]))
    add("| open disputes | {:,} |".format(view["chargeback_count"]))
    add("")
    add("### Needs action")
    add("")
    if view["alerts"]:
        add("| severity | rule | detail | action |")
        add("|---|---|---|---|")
        for a in view["alerts"]:
            add("| **{}** | `{}` | {} | {} |".format(
                a.severity, a.rule, a.detail, a.action))
    else:
        add("Nothing past a threshold on this book.")
    add("")
    t3 = sum(a.count for a in view["alerts"] if a.rule.endswith("t3"))
    add("**Totals are not actionable.** *{:,} open breaks* tells nobody what to".format(
        view["break_count"]))
    if t3:
        add("do; *{} break(s) at T3* is a morning's work with a name on it.".format(t3))
    else:
        add("do. The alerts above name what does need doing, and the count is")
        add("context for them rather than the headline.")
    add("")
    add("### A silent zero, and what it hid")
    add("")
    add("This ran once showing **{:,} open breaks** and **no break alerts at".format(
        view["break_count"]))
    add("all** on the same screen. The dashboard read `age_days` and")
    add("`break_type`; `Service.aged_breaks` returns `age` and `state`. Every")
    add("break — some **34 days old** — defaulted to age 0, landed in T0, and")
    add("raised nothing.")
    add("")
    add("A missing age must not read as NEW. Zero is the one value that means")
    add("*everything is fine*, so it is the one value a missing field must")
    add("never become. `_age_of` now accepts both names and **raises** when")
    add("neither is present, and a test asserts it raises rather than")
    add("defaulting. The break TYPE still defaults to empty, and that is safe")
    add("in a way the age is not — an unknown type misses the ledger fast-path")
    add("and ages normally, where an unknown age silently ages nothing.")
    add("")
    add("**Every alert carries an action**, taken from the tier that raised it,")
    add("so the row says what to do rather than only that something is wrong.")
    add("An alert with no action is noise, and noise is what an operator learns")
    add("to scroll past.")
    add("")

    add("### Break tiers, as the queue defines them")
    add("")
    add("| tier | from | action |")
    add("|---|---|---|")
    for name, days, action in view["tiers"]:
        add("| {} | {}+ days | {} |".format(name, days, action))
    add("")
    add("Ledger breaks start at **{}** regardless of age — `break_queue` says".format(
        TIERS[-1].name))
    add("so and the dashboard inherits it by calling `tier_for` rather than")
    add("bucketing on age itself.")
    add("")

    add("### Evidence deadlines beat amounts")
    add("")
    add("Ordered by deadline, matching `representment.work_queue`: a $200")
    add("dispute due tomorrow outranks a $2,000 one due in three weeks, because")
    add("the second can still be fought and the first cannot. Sorting a work")
    add("queue by value is the intuitive thing and it loses the winnable")
    add("disputes at the front.")
    add("")
    add("| ref | reason | amount | due | days | worth fighting |")
    add("|---|---|---|---|---|---|")
    for c in view["chargebacks"][:8]:
        add("| `{}` | {} | {:,} | {} | {}{} | {} |".format(
            c["ref"], c["reason_code"], c["amount_minor"],
            c["evidence_due_on"], c["_days"],
            " **LATE**" if c["_days"] < 0 else "",
            "yes" if c["reason_code"] in
            __import__("src.chargebacks", fromlist=["x"]).WINNABLE else "no"))
    add("")

    add("## Why it renders server-side to one file")
    add("")
    add("No CDN, no build step, no JavaScript framework, no external fetch of")
    add("any kind — a test asserts the page contains no `http://`, `https://`,")
    add("`<script` or `cdn.`.")
    add("")
    add("A settlement dashboard is looked at during an incident, and an")
    add("incident is exactly when a page that fetches a chart library from the")
    add("internet does not load. The page is also theme-aware and every value")
    add("is HTML-escaped, because a break reference comes from a settlement")
    add("file and a settlement file is input from outside.")
    add("")
    add("`/dashboard.json` returns the same view as data, because **an alert")
    add("that only exists on a screen requires somebody to be looking at the")
    add("screen.** That is the endpoint a monitoring system scrapes.")
    add("")

    add("## What this still is not")
    add("")
    add("- **Nothing pages anybody.** `/dashboard.json` is scrapeable and")
    add("  nothing scrapes it. SE-3 has the Prometheus and Alertmanager path;")
    add("  this project has the rules and not the delivery.")
    add("- **No history.** Every number is as-of. *Is this worse than")
    add("  yesterday* is the second question an operator asks and this cannot")
    add("  answer it — that needs the figures stored per run, which is a")
    add("  different job from rendering them.")
    add("- **No drill-down.** The rows name a reference; following it means")
    add("  calling `/transactions/{ref}` by hand. DATA-1 carries provenance as")
    add("  columns precisely so the drill-down is a `WHERE` clause, and this")
    add("  page does not use it.")
    add("- **One book, one operator.** No per-desk filtering, no assignment, no")
    add("  acknowledgement. An alert nobody has claimed is one everybody")
    add("  assumes somebody else has.")

    doc = "\n".join(L)
    (ROOT / "docs" / "DASHBOARD.md").write_text(doc, encoding="utf-8")
    print(doc)
    print()
    print("wrote docs/DASHBOARD.md and docs/dashboard.html")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
